sonar.projectKey=KRISTINA-Lap_python-project-49
sonar.organization=kristina-lap

# Analysis properties
sonar.sources=.
sonar.tests=.
sonar.coverage.exclusions=**/test_*.py,**/tests/**,**/__init__.py

# Test coverage
sonar.python.coverage.reportPaths=coverage.xml

# Language and encoding
sonar.language=py
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.venv/**,**/venv/**
